# Generated by Django 3.2.22 on 2024-01-10 15:45

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_contract_code_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gap_from_parent',
            field=models.IntegerField(db_column='GapFromParent', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent',
            field=models.ForeignKey(db_column='Parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_raised',
            field=models.BooleanField(db_column='PenaltyRaised', default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_raised_date',
            field=core.fields.DateField(db_column='PenaltyRaisedDate', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_waive_off_contract',
            field=models.BooleanField(db_column='PenaltyWaiveOffContract', default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_waive_off_contract_reason',
            field=models.CharField(db_column='PenaltyWaiveOffContractReason', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_waive_off_payment',
            field=models.BooleanField(db_column='PenaltyWaiveOffPayment', default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_waive_off_payment_reason',
            field=models.CharField(db_column='PenaltyWaiveOffPaymentReason', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='gap_from_parent',
            field=models.IntegerField(db_column='GapFromParent', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='Parent', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_raised',
            field=models.BooleanField(db_column='PenaltyRaised', default=False),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_raised_date',
            field=core.fields.DateField(db_column='PenaltyRaisedDate', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_waive_off_contract',
            field=models.BooleanField(db_column='PenaltyWaiveOffContract', default=False),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_waive_off_contract_reason',
            field=models.CharField(db_column='PenaltyWaiveOffContractReason', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_waive_off_payment',
            field=models.BooleanField(db_column='PenaltyWaiveOffPayment', default=False),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='penalty_waive_off_payment_reason',
            field=models.CharField(db_column='PenaltyWaiveOffPaymentReason', max_length=255, null=True),
        ),
    ]
