# Generated by Django 3.2.22 on 2024-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_auto_20240110_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='erp_contract_id',
            field=models.IntegerField(db_column='ErpContractID', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='erp_invoice_access_id',
            field=models.CharField(db_column='ErpInvoiceAccessID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='erp_contract_id',
            field=models.IntegerField(db_column='ErpContractID', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='erp_invoice_access_id',
            field=models.CharField(db_column='ErpInvoiceAccessID', max_length=255, null=True),
        ),
    ]
