# Generated by Django 3.2.25 on 2025-03-28 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0038_auto_20250227_1613'),
        ('insuree', '0059_auto_20241226_0907'),
        ('contract', '0023_auto_20240705_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeWaitingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waiting_period', models.PositiveIntegerField()),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
                ('policy_holder_contribution_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholdercontributionplan')),
            ],
            options={
                'db_table': 'tblInsureeWaitingPeriod',
                'managed': True,
                'unique_together': {('policy_holder_contribution_plan', 'insuree')},
            },
        ),
    ]
