# Generated by Django 3.2.25 on 2025-03-29 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0059_auto_20241226_0907'),
        ('policy', '0008_policy_is_valid'),
        ('policyholder', '0038_auto_20250227_1613'),
        ('contract', '0024_insureewaitingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contract.contract')),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.insuree')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='policy.policy')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholder')),
            ],
            options={
                'db_table': 'tblContractPolicy',
                'managed': True,
                'unique_together': {('contract', 'policy')},
            },
        ),
    ]
