# Generated by Django 3.2.25 on 2025-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_contractpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetails',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontractdetails',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
