# Generated by Django 3.2.25 on 2025-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_auto_20250415_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetails',
            name='is_new_insuree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontractdetails',
            name='is_new_insuree',
            field=models.BooleanField(default=False),
        ),
    ]
