# Generated by Django 3.2.25 on 2025-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_auto_20250418_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='use_bundle_contribution_plan_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='use_bundle_contribution_plan_amount',
            field=models.BooleanField(default=False),
        ),
    ]
