# Generated by Django 3.2.25 on 2025-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0028_auto_20250422_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='process_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('created', 'Created'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_to_create', 'Failed to Create'), ('failed_to_upload', 'Failed to Upload')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='process_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('created', 'Created'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed_to_create', 'Failed to Create'), ('failed_to_upload', 'Failed to Upload')], max_length=50, null=True),
        ),
    ]
